volumes:
  # Volume para armazenar arquivos do banco de dados.
  db_data:
  # Volumes para armazenar vídeos e imagens processadas
  videos_data:
  images_data:
networks:
  # Rede interna entre os containers.
  internal:

services:
  # Container com a API de upload de imagens
  image-upload-service:
    build:
      # Torna o diretório atual visível para o builder do container, para que possamos copiar os arquivos do projeto
      # para dentro do container.
      context: .
      # Arquivo de definição da imagem do container.
      dockerfile: Dockerfile
    ports:
      # Expondo aplicação na porta especificada na variável de ambiente PORT.
      - "${PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      DATABASE_URL: "${DATABASE_URL}"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - images_data:/usr/src/app/uploads

    # Define health check simples que só testa se o endpoint padrão está respondendo requisições.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

